services:
  backend:
    build: 
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app

  frontend:
    build: 
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    working_dir: /app
